Add sdkVersion constant to FRCore.Log class and use it instead of CFBundleShortVersionString
ForgeRock/forgerock-ios-sdk pull request #122
Opened 2022-03-03 13:58 UTC by vahancouver

So the problem we had was that we were reading the SDK bundle version from CFBundleShortVersionString in Info.plist. This was working great with cocoapods as cocoapods creates a project for each module under the main workspace. In case of SPM, we have only one project and it gets the main app's version (which is not what we want).

I have tried a few things, like adding a variable to Package.swift and using it as a value in target's build settings (I followed the way google did in the signin package) and then trying to read it in Info.plist. But that didn't work at all.

I have also just tried to hardcode it in the Info.plist in each module, but then realized that we don't include the Info.plist files in the SPM package (we even explicitly exclude them). This also could have been the reason of my previous step not working at all.

One other version the internet was suggesting, was trying to read Package.resolved file and extract the version from there (even if I managed to do so, it wouldn't work if the package was imported by a branch name and not by a version).

So I have decided to hardcode the version as a static let in FRCore.Log class (in one place only) and use that value in all the bundles where we print the the SDK version. I know this is not ideal and requires an update with every release.

2022-03-03 16:19 UTC, rodrigoareis commented on FRAuth/FRAuth/Log/FRLog.swift
> +            return "[FRAuth]" + "[\(FRCore.Log.sdkVersion)]"
Update Copyright header

2022-03-03 16:19 UTC, rodrigoareis commented on FRAuthenticator/FRAuthenticator/Log/FRALog.swift
> +            return "[FRAuthenticator]" + "[\(FRCore.Log.sdkVersion)]"
Update Copyright header

2022-03-03 16:20 UTC, rodrigoareis commented on FRCore/FRCore/Log/Log.swift
> +    /// Current SDK version. We hard code it here as currently there is no other way to get it dinamically when used with SPM
Update Copyright header

2022-03-03 16:20 UTC, rodrigoareis commented on FRProximity/FRProximity/Log/FRPLog.swift
> +            return "[FRProximity]" + "[\(FRCore.Log.sdkVersion)]"
Update Copyright header

2022-03-03 16:20 UTC, rodrigoareis requested changes
Changes looks good to me, missing copyright header updates

2022-03-03 18:23 UTC, vahancouver commented on FRAuth/FRAuth/Log/FRLog.swift
> +            return "[FRAuth]" + "[\(FRCore.Log.sdkVersion)]"
done ✅

2022-03-03 18:24 UTC, vahancouver commented on FRAuthenticator/FRAuthenticator/Log/FRALog.swift
> +            return "[FRAuthenticator]" + "[\(FRCore.Log.sdkVersion)]"
done ✅

2022-03-03 18:24 UTC, vahancouver commented on FRCore/FRCore/Log/Log.swift
> +    /// Current SDK version. We hard code it here as currently there is no other way to get it dinamically when used with SPM
done ✅

2022-03-03 18:24 UTC, vahancouver commented on FRProximity/FRProximity/Log/FRPLog.swift
> +            return "[FRProximity]" + "[\(FRCore.Log.sdkVersion)]"
done ✅

2022-03-03 18:31 UTC, rodrigoareis approved these changes
Looks good to me

2022-03-07 20:44 UTC, spetrov approved these changes
Looks good to me! 👍🏻

2022-03-07 23:08 UTC, merged