Remove response header from /authorize GET call
ForgeRock/forgerock-ios-sdk pull request #126
Opened 2022-04-13 02:59 UTC by vahancouver

Remove _accept: application/x-www-form-urlencoded_ header from /authorize endpoint for GET requests

I checked Android SDK. They don't send any response header.

2022-04-13 11:29 UTC, george-bafaloukas-forgerock approved these changes
Looks good mate. In case you have some time it might be worth adding a test on that

2022-04-14 00:36 UTC, vahancouver commented
> Looks good mate. In case you have some time it might be worth adding a test on that

@george-bafaloukas-forgerock Added a unit test to check if the "Accept" header is nil

2022-04-14 16:14 UTC, spetrov requested changes
Changes look good to me! 
I have some minor comments to update the copyright headers of some files that have been updated.
Also, please, update the CHANGELOG.md with a note about this fix.

2022-04-14 16:14 UTC, spetrov commented on FRAuth/FRAuth/Config/OAuth2Client.swift
> +        return Request(url: self.serverConfig.authorizeURL, method: .GET, headers: header, urlParams:parameter, requestType: .urlEncoded, responseType: nil, timeoutInterval: self.serverConfig.timeout
Please update the copyright header of the file with current year

2022-04-14 16:14 UTC, spetrov commented on FRAuth/FRAuthTests/FRAuthSwiftTests/FRAuth/FRAuth/FRAuthTests.swift
> +    func testOAuth2ClientAuthorizeCallDoesntContainAcceptHeader() {
Update copyright header, please.

2022-04-14 16:14 UTC, spetrov commented on FRCore/FRCore/Network/Request.swift
> +    public let responseType: ContentType?
Please, update the copyright header in the file

2022-04-14 18:11 UTC, spetrov approved these changes
👍🏻

2022-04-14 18:40 UTC, merged