Sdks 1491 expired push notification displayed as approved
ForgeRock/forgerock-ios-sdk pull request #128
Opened 2022-04-25 16:05 UTC by vahancouver

Fix the bug when expired notification would show up as approved
Move saving notification to the storage to the request success block (similar to Android) - this also fixed the failing tests after the first commit

2022-04-25 22:54 UTC, spetrov requested changes
Looks good to me! 
I have only one minor comment...

2022-04-25 22:54 UTC, spetrov commented on FRAuthenticator/FRAuthenticator/Model/Notification/PushNotification.swift
>      ///   - result: Boolean indicator whether or not PushNotification authentication is approved or denied
Since the parameter name was changed, please update the name in the inline docs as well (i.e. "result" -> "approved")

2022-04-25 23:30 UTC, spetrov approved these changes
👍🏻

2022-04-26 16:18 UTC, rodrigoareis approved these changes
Changes looks good to me

2022-04-26 16:23 UTC, merged