SDKS-2563 - Making "refresh" and "refreshSync" methods Public
ForgeRock/forgerock-ios-sdk pull request #220
Opened 2023-06-30 15:28 UTC by george-bafaloukas-forgerock

- Making "refresh" and "refreshSync" methods Public
- Updating tests

# JIRA Ticket

Please, link jira ticket here.
SDKS-2563

2023-07-03 14:15 UTC, jeyanthanperiyasamy approved these changes

2023-07-04 15:21 UTC, vahancouver approved these changes
Changes look good

2023-07-04 21:44 UTC, spetrov requested changes
@george-bafaloukas-forgerock, the changes look good to me. 
However, during testing, I realized that refreshing the access_token does not revoke the previous one. I thought AM would automatically invalidate it, but it only invalidates the refresh_token... 
It looks to me it is up to the client to revoke the old access_token, and we currently don't do that, so I would like to discuss this with you and the team before merging and releasing this change...

Here are the relevant parts from RFC 6749:
- [Section 1.5 Refresh Token](https://datatracker.ietf.org/doc/html/rfc6749#section-1.5)

> Refresh tokens are issued to the client by the authorization server and are
   used to obtain a new access token when the current access token
   becomes invalid or expires, **or to obtain additional access tokens**
   with identical or narrower scope

- [Section 6 Refreshing an Access Token](https://datatracker.ietf.org/doc/html/rfc6749#section-6)

> The authorization server **MAY** revoke the old
    refresh token after issuing a new refresh token to the client.

2023-07-05 18:22 UTC, spetrov approved these changes

2023-07-05 18:23 UTC, merged