FRURLProtocol ignores ssl pinning
ForgeRock/forgerock-ios-sdk pull request #282
Opened 2024-06-03 10:30 UTC by george-bafaloukas-forgerock

# JIRA Ticket

Please, link jira ticket here.](https://bugster.forgerock.org/jira/browse/SDKS-3239)

# Description

Fix for SSL Pinning and FRURLProtocol uses

2024-06-03 16:15 UTC, jeyanthanperiyasamy commented
can we add some tests around this for both success and failure cases?

2024-06-03 16:15 UTC, jeyanthanperiyasamy requested changes
comments provided

2024-06-03 16:44 UTC, george-bafaloukas-forgerock commented
> can we add some tests around this for both success and failure cases?

Might a bit hard to get proper success for SSL Pinning, unless we set on the tests the keyhashes of the test server

2024-06-03 18:31 UTC, rodrigoareis commented on FRAuth/FRAuth/Network/FRURLProtocol.swift
> +    @objc public static var frSecurityConfiguration: FRSecurityConfiguration?
Missing doc

2024-06-03 18:32 UTC, rodrigoareis requested changes
Overall changes looks good. Just minor comment to address

2024-06-04 14:36 UTC, george-bafaloukas-forgerock commented
> Overall looks good.
> 
> Can you please explain why we need this part (I see you added it later) else { completionHandler(.performDefaultHandling, nil) return } we didn't have this before adding the ssl pinning part.

Yes I had to add this, as I have added the 
```func urlSession(_ session: URLSession, task: URLSessionTask, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void)```
Method and on some requests it might return other types of `authenticationMethod`. We need to allow `defaultHandling` for the rest otherwise this will not call the `completion` and will be an API misuse. This was found through the test

2024-06-04 15:05 UTC, vahancouver approved these changes
LGTM

2024-06-04 15:35 UTC, rodrigoareis approved these changes
Looks good to me

2024-06-04 21:32 UTC, merged