Sdks 1031 cicd
ForgeRock/forgerock-ios-sdk pull request #91
Opened 2021-05-17 16:55 UTC by jhoongo

2021-05-17 18:12 UTC, rodrigoareis commented on FRCore/FRCoreTests/FRCore/Util/KeychainServiceTests.swift
> +    override func setUp() {
Update copyright

2021-05-17 18:13 UTC, rodrigoareis commented on FRTestHost/FRTestHost/SharedTestFiles/BaseTest/FRAuthBaseTest.swift
> -    var config: Config = Config()
Update copyright

2021-05-17 18:13 UTC, rodrigoareis commented on FRTestHost/FRTestHost/SharedTestFiles/BaseTest/FRBaseTestCase.swift
> +
Update copyright

2021-05-17 18:14 UTC, rodrigoareis commented on FRTestHost/FRTestHost/SharedTestFiles/TestConfig/Config.swift
> +    @objc var keychainAccessGroup: String?
Update copyright

2021-05-17 18:15 UTC, rodrigoareis requested changes
All changes looks good, just need to update the header for some changed files

2021-05-17 22:40 UTC, spetrov submitted a review, later dismissed
Looks good to me!

2021-05-18 10:03 UTC, george-bafaloukas-forgerock approved these changes
Looks good

2021-05-18 16:23 UTC, jhoongo commented
> All changes looks good, just need to update the header for some changed files

Copyright header is updated :)

2021-05-18 16:58 UTC, rodrigoareis approved these changes
Changes looks good to me

2021-05-18 17:13 UTC, merged